services:
  app:
    container_name: aspnet-techboost-aspnet-task
    image: techboost-aspnet
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
        restart: true
  
  db:
    container_name: postgres-techboost-aspnet-task
    image: postgres:17.2-alpine3.21
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: techboost_aspnet_task_db
    ports:
      - "5432:5432"
